### ISSUE TITLE
Add link to Cheatsheet

### ISSUE THREAD

**Issue by ColauttiLab** [yihanwu/baRcodeR#14]
I was inspired by RStudio's Help-> Cheatsheets -> ... menu items, which just point to web links of downloadable pdf cheatsheets. 

The same can be done as another option in the BARCODER Addins menu item:

BARCODER
------------
baRcodeR GUI
baRcodeR Cheatsheet

Here is the direct link to the pdf on Figshare:
https://ndownloader.figshare.com/files/14087612

**Comment by yihanwu** [comment]
#18
