### ISSUE TITLE
Generate barcode in a shiny app

### ISSUE THREAD

**Issue by mkaranja** [yihanwu/baRcodeR#21]
Hi,
How would I generate and download barcodes in a shiny app?
I have included create_pdf inside a download handler and it doesn't seem to work

output$downloadlabels <- downloadHandler(
    
    content = function(file) {
      create_PDF(user=FALSE, Labels=yamdata$PlantName, name ="mylabels",
                   type="matrix", ErrCorr = "H", Fsz=5)
    }
  )

Thanks,
Margaret

**Comment by mkaranja** [comment]
Figured it out

**Comment by iamluisgb** [comment]
Hello, I have the same problem. How it is work? thank you for your answer.

**Comment by mkaranja** [comment]
There is a shiny app example, https://github.com/yihanwu/baRcodeR_webapp/blob/master/app.R
