### ISSUE TITLE
Encoded information is different from input

### ISSUE THREAD

**Issue by mkaranja** [yihanwu/baRcodeR#23]
Hello,
My input variable has underscores eg. TDr14020774_1030_3_Bag36
On using custom_create_PDF(), the barcode is generated. On scanning it, it has dashes i.e TDr14020774-1030-3-Bag36
Thanks

**Comment by yihanwu** [comment]
Hi @mkaranja,

Can I confirm you are generating a qrcode label and not a linear one?

The qrcode character set we use, from the qrcode package, doesn't include the underscore. Any labels with an underscore cannot be generated so one part of the baRcodeR function replaces underscores with hypens.
