### ISSUE TITLE
qrcode no value in alphanumeric table for underscore

### ISSUE THREAD

**Issue by yihanwu** [yihanwu/baRcodeR#4]
An underscore in the label text will lead to an error of  Error in dataStringValue[x] * 45 : 
  non-numeric argument to binary operator.

Suggested fix: Check all labels during barcode_make when creating Xtxt by gsub. Replace all underscores with dashes

**Comment by ColauttiLab** [comment]
Thanks Yihan for fixing this in the latest release on CRAN (v0.1.1), replacing underscores with dashes.
