### ISSUE TITLE
Feature Request: Please add support for actual 1D barcodes

### ISSUE THREAD

**Issue by andresrcs** [yihanwu/baRcodeR#6]
This is a very useful idea but it could have even broader applications if It would have the option to use 1D barcodes.
I'm currently forced to use reticulate, python-barcode and manual editing of the knited document, for generating labels with 1D barcodes.

**Comment by sfd99** [comment]
Agree!. 
Very useful idea...1D barcode generation.

**Comment by ColauttiLab** [comment]
Funny enough, our very first algorithms were for 1D barcodes, but we moved to 2D because of character limits. We'll definitely add 1D barcodes to a future release, thanks!

**Comment by yihanwu** [comment]
Github version can now do linear code-128 barcodes. Use `type = "linear"` in `create_PDF` or `custom_create_PDF`.

**Comment by andresrcs** [comment]
Any chance you could consider other 1D barcode formats? like EAN14, EAN13, EAN8, UPCA
________________________________

**Comment by ColauttiLab** [comment]
We would certainly consider it. Can you explain why you want this? The formats you list are numeric whereas code128 is alphanumeric so it can encode anything from EAN14, EAN13, EAN9, UPCA, and should work with any run-of-the-mill barcode scanner.

**Comment by andresrcs** [comment]
I like to take advantage of barcodes already present on the stuff I'm keeping track of, so I only use my internal CODE128 barcodes when there is no other choice.
________________________________
