### ISSUE TITLE
simple question: saving the Preview-generated data to a regular data frame in the R environment?

### ISSUE THREAD

**Issue by sfd99** [yihanwu/baRcodeR#7]
This pkg is truly great 
and useful.
Using it with Rstudio in Linux.

**Q:**
I don't need to always save the  Preview-generated data
to a CSV file.

Sometimes, **using the addin**,
I simply need to save
the data visible in the pgk addin "Preview" area
(on the right-side),
to a _regular data frame_ in the R environment?.

Would be very useful for a regular data frame 
to contain all the data as shown in the addin "Preview" area,
for either 
the **unique_ID_maker** or the  **unique_hier_maker** functions.

How to do that in baRcodeR via the addin?
thanks!
**_SFd99
San Francisco_**

**Comment by ColauttiLab** [comment]
We're glad you find baRcodeR useful! Not sure if I'm understanding your question 100%, but if you want to work with a data.frame in R containing your ID codes then you can just assign an object name and cut-and-paste from the reproducible code box:
MyDataFrame<-uniqID_hier_maker(...)

Be sure to load the library first:
library(baRcodeR)
